# Generated by Django 5.0.6 on 2024-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_awards_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='years',
            field=models.CharField(max_length=20, verbose_name='Yili'),
        ),
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.CharField(max_length=20, verbose_name='Yili'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.CharField(max_length=20, verbose_name='Yili'),
        ),
    ]
